const SET_INITIAL_PROFILES = 'SET_INITIAL_PROFILES';
const ARCHIVE_PROFILE = 'ARCHIVE_PROFILE';
const ACTIVE_PROFILE = 'ACTIVE_PROFILE';

export { SET_INITIAL_PROFILES, ARCHIVE_PROFILE, ACTIVE_PROFILE };

